server:
  port: 7900
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hfuu.springcloud.entity
spring:
  datasource:
    url: jdbc:mysql://111.230.131.178:3306/springcloud
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka