server:
  port: 7900
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hfuu.springcloud.entity
spring:
  datasource:
    url: jdbc:mysql://111.230.131.178:3306/springcloud
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springcloud-provider-user    #eureka client 中 application名字

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.hfuu.springcloud: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}