# web port
server.port=8081
  # log config
logging.config=classpath:logback-spring.xml
  ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://ip:端口/xxl-job-admin
  ### xxl-job executor address
xxl.job.executor.appname=integral-zentao-job
xxl.job.executor.ip=IP地址（这里指的是XXL-JOB部署的机器，如果需要在本地测试，将此IP换成本地IP）
xxl.job.executor.port=9999
  ### xxl-job, access token
xxl.job.accessToken=
  ### xxl-job log path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
  ### xxl-job log retention days
xxl.job.executor.logretentiondays=-1